### ISSUE TITLE
Can we optimize my_configvar_check()?

### ISSUE THREAD

**Issue by Charonxin** [XmacsLabs/mogan#1017]
Is the check of my_configvar_check necessary? Seems to slow down building and running. @jingkaimori

**Comment by jingkaimori** [comment]
Yes, this function should not be introduced. Using builtin `configvar_check` is enough, but this function will run unnecessary checks before building. If @darcy-shen did have reasons to introduce this function, some necessary cache is needed to avoid repeat checks.

**Comment by jingkaimori** [comment]
https://gitee.com/XmacsLabs/mogan/issues/I800SQ

**Comment by darcy-shen** [comment]
这个问题的相关背景：https://github.com/xmake-io/xmake/issues/4173

**Comment by jingkaimori** [comment]
reverted by #1035

**Comment by jingkaimori** [comment]
reverted by https://github.com/XmacsLabs/mogan/pull/1035
