### ISSUE TITLE
Data tools don't work.

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#102]
Mogan 1.0.0 `Data->Open bibliography` doesn't respond at all.

**Comment by darcy-shen** [comment]
Simply click `Data->Open bibliography` works fine for me. Could you describe the problem in detail?

**Comment by YiqiXu** [comment]
At that time, I needed the data tools badly and couldn't make it work after trying many times. But a few days ago, it went back to normal. I have no idea why it happened. You may close the issue now.
