### ISSUE TITLE
Mogan does not launch

### ISSUE THREAD

**Issue by pdiazs** [XmacsLabs/mogan#1024]
### Mogan Version

1.1.5

### Operating System Version and Architecture

Windows 10 Home

### Describe Bug

Mogan has stopped launching. neither if I click on the icon or on the exe file. I have restarted windows and start failure proof
I have tried reinstalling different versions and no result
I have installed the alfa version 1.2.0 with the same result.I tried with administative privileges. No work
I cannot figure out what is happening: firewall?, path?. Texmacs works properly.
regards

### Expected Behavior

The program to launch

**Comment by darcy-shen** [comment]
Try https://github.com/XmacsLabs/mogan/releases/tag/v1.1.6-rc2. If it is related the corruption of cache, it should be fixed by v1.1.6-rc2.

**Comment by pdiazs** [comment]
Hi: I have installed the v 1.1.6 rc1 as suggested. Initailly it did not work. However i have deleted directory c:/users/roaming/Appdata/xmacs and now the problem is solved. (The directory existed and showed a date on february 2023).

Regards¡¡¡¡

**Comment by darcy-shen** [comment]
I guess you only need to remove `C:/Users/xxx/AppData/Roaming/Xmacs/system`.  There are corruptions in files like preferences.scm
