### ISSUE TITLE
UPSTREAM BUG: Mogan can't be compiled under Apple M1 now :(

### ISSUE THREAD

**Issue by pan93412** [XmacsLabs/mogan#1026]
### Mogan Version

commit 44eb32605addb5eab38b97397dda9d9a063e7cce

### Operating System Version and Architecture

Darwin 22.6.0 arm64 arm, macOS Ventura 13.5.2

### Describe Bug

https://github.com/tboox/tbox/issues/236

### Expected Behavior

It should be buildable :(

**Comment by darcy-shen** [comment]
It should be fixed by #1033 and  #1034
