### ISSUE TITLE
Failed to convert title to HTML

### ISSUE THREAD

**Issue by Charonxin** [XmacsLabs/mogan#1030]
### Mogan 版本

branch-1.2

### 操作系统版本和架构

ubuntu22.04 on wsl2

### 描述问题

在branch-1.2分支，执行完`xmake build && xmake install research && xmake run research`后，输入标题后，对标题字段执行Edit ->copy to -> HTML 无法复制为html文档

log：
```
;* first argument, #f, is boolean but should be a number
;    (string->number val)
;    /home/charon/mogan/build/packages/app.mogan/share/Xmacs/progs/kernel/boot/ahash-table.scm, line 926, position: 34120
; tmhtml-with-font-size: (string->number val) ; val: ""
; tmhtml-with-font-size: ((x (* (string->nu...
; tmhtml: ((tmhtml-implicit-compound x))
; tmhtml-doc-title-block: (apply-values (tm... ; l: ((with "font-size" '(error "bad...
```

### 期待的结果

正常复制为类似html文本：

**Comment by Charonxin** [comment]
func: tmhtml-with-font-size

```
(define (tmhtml-with-font-size val arg)
  (ahash-with tmhtml-env :mag val
    (let* ((x (* (string->number val) 100))
           (c (string-append "font-size: " (number->string x) "%"))
	   (s (cond ((< x 1) "-4") ((< x 55) "-4") ((< x 65) "-3")
		    ((< x 75) "-2") ((< x 95) "-1") ((< x 115) "0")
		    ((< x 135) "+1") ((< x 155) "+2") ((< x 185) "+3")
		    ((< x 225) "+4") ((< x 500) "+5") (else "+5"))))
      (cond (tmhtml-css? `((h:font (@ (style ,c)) ,@(tmhtml arg))))
            (s `((h:font (@ (size ,s)) ,@(tmhtml arg))))
            (else (tmhtml arg))))))
```

似乎val不能正常取到值？

**Comment by Charonxin** [comment]
这里的val传了一个空值，导致了这个bug，原因应该是`ahash-with`这个函数，是不是因为这个函数定义在`TeXmacs/progs/kernel/boot/ahash-table.scm`中，所以没有用上？

**Comment by Charonxin** [comment]
@darcy-shen

**Comment by Charonxin** [comment]
> 这里的val传了一个空值，导致了这个bug，原因应该是`ahash-with`这个函数，是不是因为这个函数定义在`TeXmacs/progs/kernel/boot/ahash-table.scm`中，所以没有用上？

不是这个问题，是因为这个val传进了空值，进string->number函数返回了#f

**Comment by darcy-shen** [comment]
你说的输入任意文本，我这边并不能复现

**Comment by darcy-shen** [comment]
在 wsl ubuntu 22.04 里面也无法复现，我输入的任意文本是 "ddd"

**Comment by Charonxin** [comment]
试试标题，


> 你说的输入任意文本，我这边（Windows 11）并不能复现

试试标题

**Comment by Charonxin** [comment]
理论上，导出后带字体大小的应该都会出现这个问题：
![image](https://github.com/XmacsLabs/mogan/assets/91298205/48c81c7e-e400-4679-9766-52e3dd1bb875)

**Comment by Charonxin** [comment]
另外还有一个不稳定的bug，刚刚遇到了第二次：

```
QXcbClipboard::setMimeData: Cannot set X11 selection owner
The X11 connection broke (error 1). Did the X11 server die?
error: execv(build/packages/app.mogan/bin/mogan) failed(1)
```

**Comment by Charonxin** [comment]
> 在 wsl ubuntu 22.04 里面也无法复现，我输入的任意文本是 "ddd"

应该是我不够严谨，好像只有标题导出有这个问题

**Comment by darcy-shen** [comment]
> The X11 connection broke (error 1). Did the X11 server die?

这个我猜测是wsl的问题，应该可以忽略
