### ISSUE TITLE
Export to picture not working

### ISSUE THREAD

**Issue by superhail** [XmacsLabs/mogan#1088]
### Mogan Version

1.1.4

### Operating System Version and Architecture

Windows 11 22631.2338

### Describe Bug

I click the "File->Export->export selection as image", and select the format png or jpeg, but no picture is generated in the selected directory.

### Expected Behavior

expect a picture of jpeg or png format to be generated.

**Comment by darcy-shen** [comment]
Thanks for reporting the bug, it will be fixed in v1.2.0 (round 2023/11/01).

**Comment by darcy-shen** [comment]
Checked, it works fine on macOS.

**Comment by darcy-shen** [comment]
It works fine in v1.2.1-rc2 on Windows.
