### ISSUE TITLE
Cannot open preferrence dialog, scheme error reported

### ISSUE THREAD

**Issue by jingkaimori** [XmacsLabs/mogan#1171]
### Mogan Version

1.2.0 branch-1.2

### Operating System Version and Architecture

Windows 10 22H2

### Describe Bug

This bug appears on branch-1.2, when opening Edit->preference... dialog, such error message is reported on console:

```
;unbound variable use-plugin-updater? in (use-plugin-updater?)
;    (use-plugin-updater?)
;    C:\Users\jingkaimori\Documents\Source\mogan\build\packages\app.mogan\data\progs\texmacs\menus\preferences-widgets.scm, line 762, position: 0
; (use-plugin-updater?)
; (($list ($aligned-item ($menu-text "Check...
; ((if (use-plugin-updater?) ($list ($align...
; (($when (use-plugin-updater?) ($aligned-i...
```

### Expected Behavior

report no bug

**Comment by darcy-shen** [comment]
It works fine for me, please `rm -rf .xmake && rm -rf build/` and try again.

**Comment by jingkaimori** [comment]
Now works fine :D
