### ISSUE TITLE
CMake: use target instead of global variables

### ISSUE THREAD

**Issue by darcy-shen** [XmacsLabs/mogan#122]
use target instead of global variables CURL_INCLUDE_DIRS, CURL_LIBRARIES

```
target_link_library(your-target PUBLIC CURL::libcurl)
```
as discussed in #119 .

**Comment by PikachuHy** [comment]
I will rewrite the `CMakeLists.txt` with a modern cmake style.

require at least cmake 5.15

**Comment by darcy-shen** [comment]
xmake seems to be a better alternative of CMake/Autotools.

We may switch to xmake when we start to work on Mogan 2.x.

https://xmake.io/#/

**Comment by darcy-shen** [comment]
closed by #131
