### ISSUE TITLE
[73_1] Portable version on Windows

### ISSUE THREAD

**Issue by wenbin-liu** [XmacsLabs/mogan#1223]
### Is your feature request related to a problem? Please describe.

Hello, right now there is no portable version on Windows for mogan. For system without admin privilege(common seen in a company), installing mogan is impossible.

### Describe the solution you'd like

Please add a portable version.

**Comment by darcy-shen** [comment]
I think v1.2.0 could be installed without admin privilege. Let me confirm it later.

**Comment by wenbin-liu** [comment]
Tha's cheering. Thanks.
