### ISSUE TITLE
Impossible to roll down to the bottom on the font selector setting page

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#126]
It's impossible to roll down to the bottom on the font selector setting page, when `Edit -> Preferences... -> Other -> Advanced font customization` is turned on. Then it's impossible to press the `Ok` bottom.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/32867606/161431562-2c8dca00-0f82-4925-af06-0776df8fdc04.png">

[Font change window lack a scroll bar on lower resolutions to confirm the font change](https://savannah.gnu.org/bugs/?62049)
[The font pop up menu is too big to click the OK button](https://savannah.gnu.org/bugs/?48209)

**Comment by cqyisbug** [comment]
the defaut setting of `Advanced font customization` is turned off.
w'll fix this flaw in a later version.

**Comment by darcy-shen** [comment]
For Mogan v1.1.1, we do not need to do anything. For v1.1.2, let us remove this option.

**Comment by darcy-shen** [comment]
Fixed by https://github.com/XmacsLabs/mogan/commit/1d36583da6c856aa772026eea7b9479e5248f604
