### ISSUE TITLE
[43_3] 转换为 latex 无法工作

### ISSUE THREAD

**Issue by lizhi10** [XmacsLabs/mogan#1417]
### Mogan 版本

1.2

### 操作系统版本和架构

Windows 11 23H2

### 描述问题

使用 Latex 转换功能后，编辑区域失去响应，但是功能区还可以点，但是等了很长时间也无法得到转换文件，程序也没有恢复响应。

### 期待的结果

正确的转换 Latex. 使用莫干的主要目的就是快速写论文，转换为tex然后经过简单修改就可以成文。这个功能至关重要。

**Comment by darcy-shen** [comment]
请提供具体的文档可复现这个问题的文档，是导出功能吧？

**Comment by lizhi10** [comment]
是导出功能，任何文件都不能成功导出，我试过比如就输入123 这种，也不行

**Comment by darcy-shen** [comment]
sorry 这个重要功能break了 后续增加一些集成测试用例 保证这个功能可用 1.2.1的发布会提前到下周 稍等

**Comment by lizhi10** [comment]
多谢多谢，自从发现了 texmacs，然后发现了莫干，我后面几乎所有的论文都是莫干写的，很大的提高了速度，避免了很多tex问题，这是一个好软件。

**Comment by darcy-shen** [comment]
多多反馈具体的latex导入导出相关功能 后续我会在这块做大量优化

**Comment by darcy-shen** [comment]
`Edit -> Copy to LaTeX`还是可以work的，可以先用这个功能应急

**Comment by darcy-shen** [comment]
已修复，请等待v1.2.1 rc1，大概下周一会发布v1.2.1-rc1

Fixed by https://github.com/XmacsLabs/mogan/pull/1418

**Comment by darcy-shen** [comment]
可以用v1.2.1-rc1应急了：https://github.com/XmacsLabs/mogan/releases/tag/v1.2.1-rc1
