### ISSUE TITLE
Build with MSVC

### ISSUE THREAD

**Issue by PikachuHy** [XmacsLabs/mogan#145]
first, we need an MSVC-version scheme interpreter.

we can build TeXmacs with Guile 1.8 or S7.

However, both of them can be built with MSVC.

[PicoScheme](https://github.com/PikachuHy/PicoScheme) is a good choice for me.

it is a small, embeddable scheme interpreter in c++17.

In particular

> The source code successfully compiles with a fairly recent GNU g++ compiler and under MS-Windows with the Visual Studio Community Edition v15 c++ compiler or the [MSYS2](http://www.msys2.org/) GNU build tools.

I can build, debug and develop the scheme interpreter.

second. // todo

**Comment by darcy-shen** [comment]
> However, both of them can be built with MSVC.

cannot?

**Comment by jingkaimori** [comment]
How to enable variant length array in MS Visual Studio CMake Project?
