### ISSUE TITLE
[65_8] meta key in emacs mode output the text "Emacs meta"

### ISSUE THREAD

**Issue by JackYansongLi** [XmacsLabs/mogan#1450]
### Mogan 版本

1.2.0

### 操作系统版本和架构

arch linux, x86-64

### 描述问题

I am using mogan 1.2.0 on arch Linux with emacs mode. When I type the meta key (alt on my keyboard), the mogan will always display the "Emacs meta" on my file. The issue only happens on arch Linux. The same problem does not happen on Macos.

### 期待的结果

No text is displayed on the file when typing the meta key.

**Comment by darcy-shen** [comment]
What is your version of Qt?

You can check it in scheme session via `(qt5-gui?)`, if it is false, it is Qt 5, else it is Qt 6.

**Comment by JackYansongLi** [comment]
> What is your version of Qt?
> 
> You can check it in scheme session via `(qt5-gui?)`, if it is false, it is Qt 5, else it is Qt 6.

The return is true:
```scheme
Scheme] (qt5-gui?) 
   #t
```

**Comment by darcy-shen** [comment]
confirmed, it will be fixed in v1.2.1

**Comment by JackYansongLi** [comment]
> confirmed, it will be fixed in v1.2.1

I am not sure if it is for the same reason: when I type shift+F5, the mogan displays "S+F5" instead of treating S+F5 as a shortcut. I am using KDE mode on arch Linux.

**Comment by darcy-shen** [comment]
it is a bug introduced in 65_8.
