### ISSUE TITLE
The "Meta+Alt+p" shortcut for "show preamble" does not work in KDE mode

### ISSUE THREAD

**Issue by JackYansongLi** [XmacsLabs/mogan#1453]
### Mogan Version

1.2.0

### Operating System Version and Architecture

Arch Linux

### Describe Bug

"Meta+Alt+p" shortcut for "show preamble" does not work in KDE mode

### Expected Behavior

Show preamble when type "Meta+alt+p"

**Comment by darcy-shen** [comment]
let me tune it before v1.2.1

**Comment by darcy-shen** [comment]
I use KDE on Linux too!

**Comment by darcy-shen** [comment]
On my KDE, `Ctrl-Alt-p` is occupied by the Chinese input method.

**Comment by JackYansongLi** [comment]
Based on my understanding for TeXmacs. Meta key is the windows key, not the Ctrl key.On Dec 16, 2023, at 2:43 AM, Darcy Shen ***@***.***> wrote:﻿
On my KDE, Ctrl-Alt-p is occupied by the Chinese input method.

**Comment by darcy-shen** [comment]
Switch to `Ctrl+Shift+P` only on KDE style.
