### ISSUE TITLE
Opt+1/2/3 (And a lot more) key bindings does not work with CJK input methods on macOS

### ISSUE THREAD

**Issue by ProfFan** [XmacsLabs/mogan#1458]
### Mogan Version

1.2.0

### Operating System Version and Architecture

macOS Sonoma 14.1

### Describe Bug

Opt+1/2/3 (And a lot more) key bindings does not work with CJK input methods. If I switch back to US input they work. Could be a key code issue.

### Expected Behavior

They should produce section titles

**Comment by darcy-shen** [comment]
`Option+1`, `Option+2`, `Option+3` can not be captured by `keyPressEvent`

**Comment by darcy-shen** [comment]
In Input Method, `Option+1` is used to append 1 to the pre-edit. For example, when you type nihao，and then if you type 1, the first candidate is committed. If you press `Option 1`, it will append 1 to nihao.

**Comment by darcy-shen** [comment]
It does not work because they are key bindings for the input method framework. You can use a more flexible IM framework to avoid this problem.

**Comment by ProfFan** [comment]
I actually just checked and this is not the case? at least on macOS Sonoma 14.1, Opt+1 2 3 does not do anything (in any input box)

> In Input Method, `Option+1` is used to append 1 to the pre-edit. For example, when you type nihao，and then if you type 1, the first candidate is committed. If you press `Option 1`, it will append 1 to nihao.

**Comment by darcy-shen** [comment]
What's your input method?

**Comment by darcy-shen** [comment]
Just upgraded to macOS, option 1 and option 2 is the same behavior.

**Comment by ProfFan** [comment]
I finally is able to reproduce this behavior:

On macOS 15.1, with TeXmacs (latest) under Unicode input, Opt+1/2/3 works only press once. However, under US input need to press 2 times to work.

With Mogan (latest) under Unicode input, Opt+1/2/3 works only if I press for 4 times. However, under US input just 1 keypress works no problem. In the keypress Debug menu, under Unicode input method, the menu only show 1 keypress for 4 total keypresses.
