### ISSUE TITLE
None but scheme plugin of TeXmacs format plugins are working

### ISSUE THREAD

**Issue by hammerfunctor** [XmacsLabs/mogan#1520]
### Mogan Version

v1.2.2

### Operating System Version and Architecture

Linux 6.6.8

### Describe Bug

Only `Scheme` shows up in `Insert -> Session`. I tried executing plugin defining codes in a scheme session but it doesn't work.

### Expected Behavior

Work as expected.

**Comment by darcy-shen** [comment]
TEXMACS_HOME_PATH is different on Mogan Research.

**Comment by hammerfunctor** [comment]
I transferred them before submitting this issue. Anyway, they now appear after a reboot.

**Comment by darcy-shen** [comment]
TEXMACS_HOME_PATH is documented here now: https://mogan.app/guide/Mogan_versus_TeXmacs.html#texmacs-home-path
