### ISSUE TITLE
Stable releases

### ISSUE THREAD

**Issue by Iey4iej3** [XmacsLabs/mogan#1622]
I would propose to isolate some releases as stable releases. The motivation is for packaging. For example, I guess that it would be desirable if the [Termux package](https://github.com/termux/termux-packages/tree/master/x11-packages/mogan) and the [Guix package](https://packages.guix.gnu.org/packages/mogan/) could be kept up to date, but the maintainers would not have infinite amount of time, thus maybe it is better to have stable releases so that at least the maintainers would not find it difficult to keep packages up to date for stable releases.

**Comment by darcy-shen** [comment]
A good idea! v1.2.0/v1.2.1/v1.2.2 are not stable releases. Because there are known issues.

**Comment by darcy-shen** [comment]
See https://mogan.app/guide/Install.html#recommended-old-releases

Always use the latest stable release or the recommended old releases.

**Comment by darcy-shen** [comment]
v1.2.5 will be the stable release for education purpose and it will be released before 2024/02/31 and be released for the spring semester.

And v1.2.5.1/v1.2.5.2 will be released after v1.2.5 if there are any feedbacks from the teachers.

**Comment by Iey4iej3** [comment]
Later on, it might be better to use release tags for stable releases, and pre-release tags for others. The current Termux bot seems to follow this rule: https://github.com/termux/termux-packages/blob/6eadd17b1bf5c21d7124ccdeb9985cd44bb4d01b/x11-packages/mogan/build.sh#L10 and https://github.com/termux/termux-packages/blob/master/scripts/bin/check-auto-update
