### ISSUE TITLE
[71_4] Show keyboard shortcuts in the menu if available.

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#164]
The keyboard shortcuts under the mode-dependent icon toolbar are not shown in Mogan. For example:

- Mogan
<img width="712" alt="image" src="https://user-images.githubusercontent.com/32867606/164555830-5b2e01dc-a993-479e-8e4e-25ea865ba910.png">

- TeXmacs
<img width="702" alt="image" src="https://user-images.githubusercontent.com/32867606/164556026-4c81ea95-340e-41fc-a4bb-c9ab2ca01cbf.png">

**Comment by PikachuHy** [comment]
The keyboard shortcuts are shown.

![image](https://user-images.githubusercontent.com/18223871/164465885-26ea5785-a029-45a4-8fcf-ee70f14efb41.png)

**Comment by darcy-shen** [comment]
The key is this property: https://doc.qt.io/qt-6/qaction.html#shortcutVisibleInContextMenu-prop

**Comment by darcy-shen** [comment]
Fixed by #1376
