### ISSUE TITLE
Large brackets issue with Stix font

### ISSUE THREAD

**Issue by avogab** [XmacsLabs/mogan#1682]
### Mogan Version

1.2.5-rc2

### Operating System Version and Architecture

Kubuntu 22.04

### Describe Bug

Large brackets are not displayed correctly with Stix font. Log:

TeXmacs] warning, no bitmap available for <#239E>
TeXmacs]   in font unicode:STIXSizeOneSym-Regular10@600
TeXmacs] warning, no bitmap available for <#23A0>
TeXmacs]   in font unicode:STIXSizeOneSym-Regular10@600
TeXmacs] warning, no bitmap available for <#239F>
TeXmacs]   in font unicode:STIXSizeOneSym-Regular10@600

A minimal file content to reproduce the issue:

<style|<tuple|generic|no-page-numbers|british>>

<\body>
  <\equation*>
    <around*|(|<frac||>|)>
  </equation*>

  \;
</body>

<\initial>
  <\collection>
    <associate|font|stix>
    <associate|font-family|rm>
    <associate|math-font|math-stix>
    <associate|page-medium|paper>
    <associate|page-screen-margin|false>
  </collection>
</initial>

### Expected Behavior

The brackets should adapt to content that has more rows.

**Comment by da-liii** [comment]
Here is the screenshot to reproduce the issue:
![image](https://github.com/user-attachments/assets/28679e8e-293d-4374-8ab0-bb786302de0d)

**Comment by da-liii** [comment]
![image](https://github.com/user-attachments/assets/bebf4dc9-0501-4527-b5ac-ed05d73938a2)

should be fixed by https://github.com/XmacsLabs/mogan/pull/2120

**Comment by da-liii** [comment]
Here is the test doc in TMU:
```
<TMU|<tuple|1.0.5|1.2.9.5>>

<style|<tuple|generic|british>>

<\body>
  Stix:

  <with|font|Stix Math|<\equation*>
    <around*|(|<frac|1|2+<frac|1|2>>|)>
  </equation*>>

  Roman:

  <\equation*>
    <around*|(|<frac|1|2+<frac|1|2>>|)>
  </equation*>
</body>

<\initial>
  <\collection>
    <associate|page-screen-margin|false>
  </collection>
</initial>
```

**Comment by avogab** [comment]
Great ! Thanks @KeShih and @da-liii
