### ISSUE TITLE
Debian packaging: the minor version is not recorded

### ISSUE THREAD

**Issue by Iey4iej3** [XmacsLabs/mogan#1771]
### Mogan Version

1.2.5.1

### Operating System Version and Architecture

Debian bookworm

### Describe Bug

In the Debian package of mogan v1.2.5.1, the minor version `.1` is not recorded:

```
Unpacking mogan-research (1.2.5-1) over (1.2.5-1)
```

### Expected Behavior

The version should be corrected recorded.

**Comment by darcy-shen** [comment]
Fixed by https://github.com/XmacsLabs/mogan/commit/c1358fdf9b114071b3725a9d0ddf71ff72bdf0ff
