### ISSUE TITLE
No support for RPM package?

### ISSUE THREAD

**Issue by 9ao9ai9ar** [XmacsLabs/mogan#1841]
### Mogan Version

None

### Operating System Version and Architecture

Fedora 38 x86_64

### Describe Bug

How do I install this software on Fedora or other Red  Hat-based Linux distributions? Neither RPM package nor tarball is provided for installation.

### Expected Behavior

I expect Mogan to be usable on RHEL, the main Linux distribution and which AlmaLinux, used by CERN and many other scientific communities, is based on. A rather recent version of TeXmacs is available on the main Fedora repository, so why can't Mogan follow suit?

**Comment by da-liii** [comment]
>  why can't Mogan follow suit?

Just too busy to make the RPM package. I'm trying to make it available in v1.2.9.7.

**Comment by da-liii** [comment]
@9ao9ai9ar I'm setting up the CD on Fedora 41, if you are still using Fedora 38, you can build the rpm by yourself following the github action steps: https://github.com/XmacsLabs/mogan/blob/branch-1.2/.github/workflows/cd_research_on_fedora.yml

**Comment by da-liii** [comment]
See https://github.com/XmacsLabs/mogan/releases/tag/v1.2.9.7-rc4

rpm package for Fedora 41 is available since v1.2.9.7-rc4.
