### ISSUE TITLE
The wide tilde in Stix font is not displayed properly.

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#198]
- TeXmacs

<img width="207" alt="image" src="https://user-images.githubusercontent.com/32867606/166346526-bed1fb3a-5153-408f-849d-991a8bf5b9c0.png">

- Mogan

<img width="350" alt="image" src="https://user-images.githubusercontent.com/32867606/166347462-c830287b-58ce-4997-9a38-6e01759c5189.png">

I am using Mogan v1.0.2 and you can change the font to Stix as follows

<img width="446" alt="image" src="https://user-images.githubusercontent.com/32867606/166632675-e74b8b02-3218-417e-beab-a8b5c6bce8d3.png">

**Comment by darcy-shen** [comment]
Fixed by #227
