### ISSUE TITLE
\mathbbm is not working in the math mode.

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#205]
In Mogan v1.0.2 the `\mathbbm` is not working in math mode, e.g.

- Text mode
<img width="355" alt="image" src="https://user-images.githubusercontent.com/32867606/166696087-de085400-185d-4eb9-a54d-8cd55c0d57a4.png">

- Math mode
<img width="288" alt="image" src="https://user-images.githubusercontent.com/32867606/166696223-63d735a1-339b-4470-8167-8e3af3ddef5a.png">

**Comment by darcy-shen** [comment]
#176 is the root cause.

**Comment by darcy-shen** [comment]
Fixed by #227
