### ISSUE TITLE
请问 mogan 的快捷键和 texmacs 的异同点是什么呢？

### ISSUE THREAD

**Issue by lizhi10** [XmacsLabs/mogan#2092]
比如，我想打 Kähler，在 Windows 下，按 esc+shift+" 然后按 a，就可以把 ä 打出来，但是 mogan 却不行。
还有一些数学按键，比如在无框表格里增加列，在 texmacs 里，按 esc+键盘左键，就可以加一列，但是 mogan 也不行。

**Comment by da-liii** [comment]
官网有说明：https://mogan.app/zh/guide/Mogan_versus_TeXmacs.html#%E5%BF%AB%E6%8D%B7%E9%94%AE

**Comment by da-liii** [comment]
>  还有一些数学按键，比如在无框表格里增加列，在 texmacs 里，按 esc+键盘左键，就可以加一列，但是 mogan 也不行。

墨干里面使用 `Alt+方向键`，我认为这是texmacs设计上的问题，实际上是用 esc 来模拟 meta，但这里应该直接用 alt

**Comment by lizhi10** [comment]
> 关于ESC键，墨干官网有说明：https://mogan.app/zh/guide/Mogan_versus_TeXmacs.html#%E5%BF%AB%E6%8D%B7%E9%94%AE
> 
> > 比如，我想打 Kähler，在 Windows 下，按 esc+shift+" 然后按 a，就可以把 ä 打出来，但是 mogan 却不行。
> 
> 我们最近在整理文档，要得到 ä ，在linux上用 meta+shift+" 然后按 a是没问题的。Windows上不知道这个快捷键能否生效

Windows 用alt+shift+" 打不出来。
我觉得是不是弄一个texmacs兼容模式，包括快捷键，tm/tmu文件格式什么的都保持兼容，因为很多人都是从texmacs迁移归来的，弄得特别不一样是不是增加使用难度？

**Comment by da-liii** [comment]
> tm/tmu文件格式什么的都保持兼容

tm格式本来就是兼容的，tmu格式目前还没有贡献到GNU TeXmacs，未来GNU TeXmacs也会支持tmu格式
