### ISSUE TITLE
macOS 打开帮助文档响应时间过长

### ISSUE THREAD

**Issue by lethefrost** [XmacsLabs/mogan#2116]
### Mogan Version

v1.2.9.2

### Operating System Version and Architecture

macOS Sequoia 15.0；arm64

### Describe Bug

点击菜单栏>帮助的任何一项文档之后，都会陷入好几分钟的应用程序没有响应状态。我一开始还以为会导致整个卡死，重启了几次尝试不同文档均无响应之后就放置了一会儿，再回去看发现只是加载时间过长。大概需要2-5分钟不等。

### Expected Behavior

应该和读取其他外部文档速度相近才比较符合预期吧……？打开其他文件几乎都是秒开。

**Comment by da-liii** [comment]
帮助菜单下面的文档是托管在阿里云服务器上的，暂时没有配置CDN，v1.2.9.3会解决这个问题。

慢的原因主要是网速，特别是在中国大陆之外。

**Comment by da-liii** [comment]
v1.2.9.3已经发布，这个问题已经解决了。
