### ISSUE TITLE
Default interface layout: back to the TeXmacs original

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#212]
Using v1.0.2 for a couple of days, I should admit that putting the mode-dependent icon toolbar vertically on the left is not as good as I expected.

1. In the math mode, my screen is too small to show all toolbar items vertically, and I have to click one more time to get the table and graphics tool every time, which is quite inconvenient.
<img width="121" alt="image" src="https://user-images.githubusercontent.com/32867606/166930679-2e9a0d1f-0ba1-406e-b261-9a93401d7306.png">

2. When I drag it back to the original horizontal position, Mogan cannot save the layout. I have to do it again every time I open Mogan. 

I suggest keeping the left vertical position as an option, but the horizontal as default, back to the days before.

**Comment by darcy-shen** [comment]
See #174 for 1

And for 2, it would always be nice to have an configuration. And we should provide a button for use to reset back to the original GNU TeXmacs UI.
