### ISSUE TITLE
Code in Help is broken

### ISSUE THREAD

**Issue by ProfFan** [XmacsLabs/mogan#2203]
### Mogan Version

1.2.9.7

### Operating System Version and Architecture

macOS

### Describe Bug

<img width="803" alt="image" src="https://github.com/user-attachments/assets/a5f594e7-4191-4dc1-b94e-4b820a12220b">

### Expected Behavior

Should show the correct symbols

**Comment by da-liii** [comment]
Click `Tools->Fonts->Clear font cache` and restart Mogan.

It is caused by the built-in fonts change. We just make CMU font and Latin Modern Math font built-in.
