### ISSUE TITLE
When saving and naming a file, copy-and-paste is not working.

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#231]
When saving a file, paste doesn't work in `Save As` input field, no matter if I copy texts from a `tm`-file or somewhere else.

![image](https://user-images.githubusercontent.com/32867606/168826599-dfa948df-7c49-4f63-8e8f-6cbe68c6fe37.png)

**Comment by darcy-shen** [comment]
Fixed by #1444, but we have to use the Qt-style dialogue for now.
