### ISSUE TITLE
A "post-modern" icon style

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#250]
[A "post-modern" icon style for TeXmacs](https://github.com/texmacs/tm-forge/tree/main/miscellanea/post-modern-icons)
Related to the first point of #4.

**Comment by darcy-shen** [comment]
We have adopt KDE Breeze Icons for the Main/Mode toolbar.

**Comment by darcy-shen** [comment]
We still have to complete https://github.com/XmacsLabs/mogan/issues/329 later.
