### ISSUE TITLE
broken dark mode UI for macOS

### ISSUE THREAD

**Issue by darcy-shen** [XmacsLabs/mogan#27]
![image](https://user-images.githubusercontent.com/1267865/147931309-e629abb8-1fbc-45fe-894b-677822936ea6.png)

**Comment by YiqiXu** [comment]
The dark mode works much better on Mogan v1.0 alpha3 for macOS.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32867606/147986593-7cda57bf-692d-4de3-8d57-082dcc285a84.png">
