### ISSUE TITLE
should depends on libgs but not the ghostscript binary

### ISSUE THREAD

**Issue by darcy-shen** [XmacsLabs/mogan#294]
```
sudo apt install libgs-dev
```
+ [x] tm_gs should be removed
+ [ ] src/Plugins/gs_utilities.cpp
   + [ ] gs_version
   + [ ] gs_image_size
   + [ ] gs_PDFimage_size
+ [ ] packager for Linux and Windows could be simplified
+ [ ] add libgs-dev for ubuntu ci
+ [ ] init-image.scm 

Subticket of #288

**Comment by jingkaimori** [comment]
there are no libgs package on xrepo for mingw or msys, this issue may be postponed.
