### ISSUE TITLE
Default Chinese font in Linux

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#298]

**Comment by taoky** [comment]
Maybe the instruction of installing Fandol fonts should be translated to English and be put to a more obvious place, as by default no CJK characters can be shown in mogan under Linux platform.

**Comment by darcy-shen** [comment]
We are working on supporting Noto CJK. Fandol should be the the default CJK font on GNU/Linux.

**Comment by darcy-shen** [comment]
closed by #447
