### ISSUE TITLE
The GUI of mogan 1.0.4 does not display on windows

### ISSUE THREAD

**Issue by zxhd863943427** [XmacsLabs/mogan#299]
OS：windows 10 Professional
Before the day before yesterday, the GUI of mogan 1.0.4 was normally available.
In the virtual machine created by hyper-v, the GUI of mogan 1.0.4 is also available normally.
Currently using texmacs at the same time, its GUI displays fine.
I think there may be some problems with my current system configuration, can someone give me some directions for troubleshooting?

------------------------------------------------------------------------------------
系统版本：windows 10 专业版
在前天之前，mogan 1.0.4 的GUI是正常可用的。
在 hyper-v 创建的虚拟机中，mogan 1.0.4 的GUI也是正常可用的。
目前同时使用了texmacs，它的GUI显示正常。
我认为可能是我目前的系统配置出了些问题，有人能给我一些排查的方向吗？

**Comment by darcy-shen** [comment]
You can reset Mogan Editor like

See https://jingyan.baidu.com/article/75ab0bcb08286d97864db2db.html

Note: please replace `%appdata/TeXmacs` with `%appdata/Xmacs`.

**Comment by zxhd863943427** [comment]
yes, it work!
I haven't figured out what's going on yet, but thank you!
