### ISSUE TITLE
No glyph for Chinese word

### ISSUE THREAD

**Issue by hammerfunctor** [XmacsLabs/mogan#311]
Chinese now correctly get encoded as unicode, but Mogan cannot find glyph. Is it still necessary to grab Chinese data file and put it in my `.Xmacs` dir like TeXamcs?

Manually build from Github repo on Archlinux.
```
TeXmacs version 2.1.3
Mogan version 1.1.1-alpha
(c) 1999-2022 by Joris van der Hoeven and others
```
![Screenshot_20220911_161620](https://user-images.githubusercontent.com/65394269/189547406-5a0bf83c-e1f2-47f7-9fdf-74e471689fc4.png)

**Comment by darcy-shen** [comment]
Duplicated with #298
