### ISSUE TITLE
Ctrl+backspace delete a word as in Emacs

### ISSUE THREAD

**Issue by ice1000** [XmacsLabs/mogan#317]
Very useful!!

**Comment by KingJadeLight** [comment]
I use this
`("A-backspace" (begin (kbd-select traverse-left) (kbd-delete)))`

**Comment by KingJadeLight** [comment]
The complete code is the following:

`(delayed        
    (lazy-keyboard-force)
    (kbd-map
    ("A-backspace" (begin (kbd-select traverse-left) (kbd-delete)))
)
)
   `

**Comment by ice1000** [comment]
Can we have this by default

**Comment by darcy-shen** [comment]
Welcome to create a pull request!

**Comment by ice1000** [comment]
I wish I created the file at the correct place
