### ISSUE TITLE
quick way of typing `\rightsquigarrow`?

### ISSUE THREAD

**Issue by ice1000** [XmacsLabs/mogan#318]
Right now `~>` with tabs does not give this, unlike similarly `<` w/ tabs gives ∈ and stuffs. This can be useful for cubical type theory documents.

**Comment by YiqiXu** [comment]
`~``>` actually works fine on my MacBook.

**Comment by ice1000** [comment]
Did you mean `~` followed by `>`?

**Comment by YiqiXu** [comment]
> Did you mean `~` followed by `>`?

Yes.

**Comment by darcy-shen** [comment]
It should be `\rightsquigarrow`, the keybinding mentioned by YiqiXu works fine for me on Linux in math mode.

**Comment by darcy-shen** [comment]
It is documented here: https://github.com/XmacsLabs/planet/blob/main/LaTeX/MathSymbols.tm

And you can browse the math symbols and the keybindings via `Help -> Planet -> LaTeX Symbols -> Math Symbols`.
