### ISSUE TITLE
快速打开配置文件

### ISSUE THREAD

**Issue by ice1000** [XmacsLabs/mogan#323]
这个文件名比 ~/.emacs 难记多了

**Comment by darcy-shen** [comment]
请详细说明，你需要什么样的功能？

**Comment by darcy-shen** [comment]
![图片](https://user-images.githubusercontent.com/1267865/191242628-b37e72aa-9cf4-43c4-a9bc-848ca6729a52.png)

Tools菜单下面可以激活Developer菜单，然后就可以打开相关配置文件。

**Comment by ice1000** [comment]
牛逼！这就是我想要的。教程里面让我去找这个路径，还得创建文件。果然不能看教程，还是问人靠谱，哈哈
