### ISSUE TITLE
`\title` to insert title

### ISSUE THREAD

**Issue by ice1000** [XmacsLabs/mogan#350]

**Comment by YiqiXu** [comment]
The current title macro is `\doc-title`.

**Comment by ice1000** [comment]
Thanks Yiqi!

**Comment by darcy-shen** [comment]
I think the key sequence `# var` might be a good way to insert title in all styles.

**Comment by da-liii** [comment]
`\doc-title` is different with `Insert -> Chapter -> Title`, we should provide `\title` to insert a title.
