### ISSUE TITLE
Wrong font size on macOS

### ISSUE THREAD

**Issue by ProfFan** [XmacsLabs/mogan#364]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/5358374/199361169-531bae9a-272e-4cc2-9a8e-05daad327608.png">

**Comment by YiqiXu** [comment]
Thanks for your reminder. Unfortunately, the font TeX Gyre Pagella does not sufficiently support Chinese characters, and I forgot to force a suitable font on them. I have fixed it and am waiting for @darcy-shen to merge it. Hopefully, @darcy-shen can resolve this kind of problem in Version 1.1.2.
