### ISSUE TITLE
bibliography bugs

### ISSUE THREAD

**Issue by laserroger** [XmacsLabs/mogan#372]
A minimal example is attached as test.zip. There are two major problems: the long dash display and the incorrect handling of the "number" field in the bib file. 
texmacs: 
<img width="544" alt="Screenshot 2022-11-04 at 2 31 14 PM" src="https://user-images.githubusercontent.com/7451488/200049562-dcb0b683-dfaa-48d1-83a3-ed67f5ba70d3.png">
mogan: 
<img width="486" alt="Screenshot 2022-11-04 at 2 30 58 PM" src="https://user-images.githubusercontent.com/7451488/200049495-b6b1ba31-7dfc-4155-8ea0-8a485c50c034.png">
[test.zip](https://github.com/XmacsLabs/mogan/files/9941124/test.zip)

**Comment by darcy-shen** [comment]
Reproducible on Mogan v1.1.1 and v1.1.0.

**Comment by darcy-shen** [comment]
Fixed by https://github.com/XmacsLabs/mogan/commit/92c5cdd84d86db84cab15679e3332dea4c3a547a and https://github.com/XmacsLabs/mogan/commit/24a6ed5212d2b9a1c9d05425b5127e6a55355f20

**Comment by darcy-shen** [comment]
Documented in branch-1.2, see https://github.com/XmacsLabs/mogan/commit/bae3023cf03b98a1edfca6ac4705c231546d65c3
