### ISSUE TITLE
Substitute tex export's chinese support CJK package with ctex package

### ISSUE THREAD

**Issue by Sinofine** [XmacsLabs/mogan#384]
https://github.com/XmacsLabs/mogan/blob/cac2d81e32486c60a8e6092adabd76c0dbc82051/TeXmacs/progs/convert/latex/texout.scm#L116-L123

it should be better to process chinese with ctex package.

**Comment by da-liii** [comment]
Fixed now: https://gitee.com/XmacsLabs/latex/pulls/1

And now, latex import and export is maintained as a standalone repo as a data plugin.

The fix will be shipped in Mogan v1.2.9.2.
