### ISSUE TITLE
[11_11] Ligatures are not typeset properly when the language is set to Chinese

### ISSUE THREAD

**Issue by z-rui** [XmacsLabs/mogan#402]
Ligatures such as fi, fl are not typeset properly. However, in a list they are.
This only happens when the language is set to Chinese.

Source:
```
fi fl ff ffi ffl <with|font-series|bold|fi fl ff ffi ffl>
<with|font-shape|italic|fi fl ff ffi ffl>

<\itemize>
  <item>fi fl ff ffi ffl <with|font-series|bold|fi fl ff ffi ffl>
  <with|font-shape|italic|fi fl ff ffi ffl>
</itemize>
```

Output:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/7368209/205224889-bb9a6488-3d3e-4348-a016-77932ee91a88.png">

**Comment by darcy-shen** [comment]
Ligatures should be supported by font. When the language is set to Chinese, the English words are using the `sys-chinese` font. We should separate the setting for CJK and western characters.

**Comment by darcy-shen** [comment]
When is the language is chinese, there is protrusion.

https://github.com/XmacsLabs/mogan/blob/v1.1.6/src/Typeset/Line/lazy_paragraph.cpp#L552-L553

And the kerning of the text_box will be adjusted via
https://github.com/XmacsLabs/mogan/blob/v1.1.6/src/Typeset/Boxes/Basic/text_boxes.cpp#L115-L133

For english in the Chinese document, the kerning will be zero. That's how I fixed the bug.
