### ISSUE TITLE
macOS: The plist file generated by `xmake` is not as complete as what CMake generates

### ISSUE THREAD

**Issue by pan93412** [XmacsLabs/mogan#418]
- `CMake` can include our `scripts/macos/Info.plist.in` file, which includes the extensions we support in Mogan, the icon of this app, and some details of this application. However, I can not see any way to substitute the placeholder on `Info.plist.in` and include it in one step.
- The current `plist` `xmake` generates is so simple that we don't even have icon on our built app!
- We may need to write it by hand. Nevertheless, I don't even know how to include `.plist` on our script in the correct way – [this official way failed in my attempt](https://tboox.org/2020/04/27/xmake-update-v2.3.3/).
- I'm not familiar with the build system under C. Hope anyone who familiar to macOS development & xmake can help this!

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/28441561/206225933-faac1d7e-2437-4b6e-ab25-a3d60a66414a.png">

**Comment by darcy-shen** [comment]
I'm working on it tonight.

**Comment by darcy-shen** [comment]
see https://github.com/XmacsLabs/mogan/pull/419

**Comment by pan93412** [comment]
Fixed!
<img width="928" alt="image" src="https://user-images.githubusercontent.com/28441561/206737982-d12a84cc-bdfc-4a55-8af9-7f8df7a83345.png">
