### ISSUE TITLE
Windows UI scaling too large

### ISSUE THREAD

**Issue by Ye-Jinhong** [XmacsLabs/mogan#424]
![image](https://user-images.githubusercontent.com/48616668/206835589-82292216-ce3f-49c9-b9eb-5d3139b9cbb9.png)

As shown above, the toolbar is too large.

- System: Windows 11
- Mogan Version: v1.1.1

**Comment by YiqiXu** [comment]
You can customize the scaling in the following setting. Let me know if it works for you.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/32867606/206864484-924583e9-0f75-4b56-a8ba-40c54283aa61.png">

**Comment by Ye-Jinhong** [comment]
YES! It works well. And the scale is 1.666 initially.
