### ISSUE TITLE
replace wget.exe with libcurl

### ISSUE THREAD

**Issue by jingkaimori** [XmacsLabs/mogan#449]

**Comment by darcy-shen** [comment]
See #119 

Here is the only place which is invoking wget. But it will not be invoked.
`TeXmacs/progs/doc/help-funcs.scm`

**Comment by darcy-shen** [comment]
We need better integration with libcurl here: https://github.com/XmacsLabs/mogan/issues/96

**Comment by jingkaimori** [comment]
that system calling executes following command:
```bash
cd $TEXMACS_HOME_PATH;
wget ftp://ftp.texmacs.org/pub/TeXmacs/doc/TeXmacs-doc.tar.gz -O TeXmacs-doc.tar.gz;
gunzip TeXmacs-doc.tar.gz;
tar -xvf TeXmacs-doc.tar;
rm -f TeXmacs-doc.tar
```

It is hard to glue http client, unzipper and installation file updater into scheme. I would rather like to integrate another online document mechanism which uses remote document.

**Comment by darcy-shen** [comment]
> I would rather like to integrate another online document mechanism which uses remote document.

Real online document is planed, just like XmacsLabs planet, we could directly load help docs from internet. It will help us reduce the installer size.

**Comment by darcy-shen** [comment]
See: https://gitee.com/XmacsLabs/mogan/issues/I5GC0J
