### ISSUE TITLE
Slowness and sluggishness when editing inside a Theorem/Lemma/Proof environment

### ISSUE THREAD

**Issue by guraltsev** [XmacsLabs/mogan#460]
This is a bug report that follows up on the discussion on the [forum](http://forum.texmacs.cn/t/will-you-switch-from-texmacs-to-mogan-due-to-its-faster-editing-speed/1125/25)

I am comparing the latest release of TeXmacs (2.1.1) to the latest release of Mogan (1.1.1). I am working on windows 10.

Mogan is sluggish and much slower than TeXmacs even with empty/one single line files when editing inside environments (Theorem/Lemma/Proof etc).

I tried creating a new, completely empty default file. If I press and hold down the `s` key on an empty line it fills in with one character appearing at a time in quick succession. This works the same on TeXmacs and on Mogan.

Things change drastically if I am inside any environment. I create a Lemma and put myself inside and again press the `s` key. Here is where the problem happens. 

If I do this with TeXmacs it is as snappy as outside the environment. However, in Mogan things slow down drastically. The editor lags and displays the `s` letters in batches of 4-6 lettes at a time with hiccups after each batch. 

I would be glad to help debug this any way I can.

**Comment by guraltsev** [comment]
The release I got from [here](https://github.com/XmacsLabs/mogan/actions/runs/3736838804) does not have the sluggishness described above!

**Comment by darcy-shen** [comment]
Try https://github.com/XmacsLabs/mogan/releases/tag/v1.1.2-alpha4

Is it solved now?

**Comment by guraltsev** [comment]
In the specific situation I described there no lag anymore. I will open other reports if I find slowdowns w.r.t. Texmacs. Thank you!

**Comment by GiulioCocconi** [comment]
It's slower in section titles too

**Comment by guraltsev** [comment]
I think this was already the case with TeXmacs even before. I opened this bug because the speed in the environments was a regression w.r.t TeXmacs. However, you are right. Have you tried lists? Is there a slowdown there, too?

**Comment by GiulioCocconi** [comment]
List are much faster

Il giorno sab 7 gen 2023 alle ore 00:48 Gennady Uraltsev <
***@***.***> ha scritto:

**Comment by mgubi** [comment]
@darcy-shen was the problem related to my patch to s7? It would be useful to know.
