### ISSUE TITLE
Cannot install Mogan

### ISSUE THREAD

**Issue by GiulioCocconi** [XmacsLabs/mogan#485]
When I try to do `sudo xmake install` it fails with this error:
`error: install failed, cannot copy file build/linux/arm64-v8a/release/libkernel.a to /usr/local/lib/libkernel.a, Not access because it is busy`

**Comment by darcy-shen** [comment]
`sudo xmake install` is not the right way to install Mogan.

**Comment by GiulioCocconi** [comment]
ahaha. And what is the right way?

**Comment by darcy-shen** [comment]
Here is the DEV guide: https://github.com/XmacsLabs/mogan/blob/main/docs/guide/Develop_on_Linux.md

**Comment by darcy-shen** [comment]
For users, please use Mogan Editor 1.1.1:
https://mogan.app/guide/Install.html#gnu-linux
There are community contributed support for OpenSUSE and ArchLinux.

If you really want to try Mogan Editor 1.1.2 alphaX:

For Debian and Ubuntu, we suggest that you should use `packages/debian/package.sh` to create the deb package and then use `dpkg` to install the debian package.

**Comment by darcy-shen** [comment]
> sudo xmake install is not the right way to install Mogan.

## Why `sudo xmake install` is not the right way
Two reasons:
1. for this repo, the command `sudo xmake install` does not work
2. The traditional `sudo make install` is not the "right" to install a package. The problem is that it is usually hard to uninstall what is installed via `sudo make install`

**Comment by GiulioCocconi** [comment]
Thank you :) 
I suggest you to copy the docs in Github Wiki
