### ISSUE TITLE
Add Mogan to User list of Xmake

### ISSUE THREAD

**Issue by Iey4iej3** [XmacsLabs/mogan#494]
This is not an issue of Mogan, but about advertising. It seems worthwhile to add Mogan to https://github.com/xmake-io/xmake-docs/blob/master/about/who_is_using_xmake.md

**Comment by jingkaimori** [comment]
I proposed a pull request about this topic:

https://github.com/xmake-io/xmake-docs/pull/95

**Comment by Iey4iej3** [comment]
Merged.
