### ISSUE TITLE
`\underline` missing in HTML converter

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#499]
- [`\underline` missing in HTML converter](http://forum.texmacs.cn/t/underline-missing-in-html-converter/1235)
- [bug #63673](https://savannah.gnu.org/bugs/?63673): `\underline` missing in HTML converter

**Comment by darcy-shen** [comment]
It was fixed by [Philippe Joyez](https://savannah.gnu.org/users/pjoyez). 
@Charonxin, you can port it from GNU TeXmacs.
