### ISSUE TITLE
Hyperlink URL containing ampersand

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#502]
[How to insert hyperlink URL containing ampersand](http://forum.texmacs.cn/t/how-to-insert-hyperlink-url-containing-ampersand/1238)

**Comment by jingkaimori** [comment]
FIxed by [f7ba409](https://github.com/XmacsLabs/mogan/commit/f7ba4096abe60e372ce7bc9114a592f3e2342dbb)
