### ISSUE TITLE
New icon for Mogan?

### ISSUE THREAD

**Issue by mgubi** [XmacsLabs/mogan#503]
Some time ago I designed a new icon for TeXmacs. It could be nice to use it for Mogan. 
![icon_512x512@2x](https://user-images.githubusercontent.com/3253062/213194795-5e12ded7-6133-446d-a9a5-303471d79738.png)
If this is interesting I can send also the .SVG files and the MacOS icon files.

**Comment by darcy-shen** [comment]
Currently, the icon for Mogan is more about the Chinese meaning of Mo (Ink).

Your icon is a better icon! I'm interested!

**Comment by mgubi** [comment]
Great. I think would make a good icon for Mogan. And one can use it also to replace the standard TeXmacs logo in Mogan documentation.

**Comment by mgubi** [comment]
Do you have any idea for a logo with "ink"?

**Comment by darcy-shen** [comment]
closed by #504, #505, #506, #507
