### ISSUE TITLE
XMake warning when compiling for `arm`

### ISSUE THREAD

**Issue by GiulioCocconi** [XmacsLabs/mogan#525]
I was compiling `mogan 1.1.2` with my raspberry pi. At the end of the compilation phase xmake throws this warning:
`warning: target(libmogan).add_linkdirs("/usr/lib/x86_64-linux-gnu") path not found at :-1`.

**Comment by woutersj** [comment]
Same on Fedora. The directory `/usr/lib/x86_64-linux-gnu` is hardcoded in `xmake.lua`, but the path does not exist on all distributions.

**Comment by darcy-shen** [comment]
It should be fixed by #538

**Comment by woutersj** [comment]
Thanks, yes, build seems to work now.
