### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by astronmyphy** [XmacsLabs/mogan#526]
打开经常未响应   mogan版本：Pre-release v1.1.2-rc2    系统：Windows 10 IoT 企业版 LTSC 21H2

**Comment by darcy-shen** [comment]
中文文档还是英文文档，1.1.2 rc2相对于1.1.1，是否有更多的未响应？

**Comment by astronmyphy** [comment]
刚打开软件的时候就是这样  未响应  要过好一段时间才正常

**Comment by darcy-shen** [comment]
正常现象 这块后续会优化 因为初次使用字体的加载比较慢

**Comment by darcy-shen** [comment]
后续使用 理论上不会经常出现未响应这种现象 因为会有字体缓存

**Comment by Iey4iej3** [comment]
测试下重建（用户目录下，我不清楚 Windows 在何处）.Xmacs 目录，以便搞明白是否由用户设置或不正常的缓存导致。
