### ISSUE TITLE
Chinese number

### ISSUE THREAD

**Issue by ChihHao-Su** [XmacsLabs/mogan#527]
Is there any way to use Chinese number in sections, subsections, paragraph etc.?

**Comment by darcy-shen** [comment]
Currently, no way. Here is the related draft pull request: https://gitee.com/XmacsLabs/mogan/pulls/36

**Comment by darcy-shen** [comment]
```
<number|1|hanzi> -> 一
<number|2|hanzi> -> 二
```
number原语已经支持汉字数字编号，但是相关样式需要用户自己编写。目前只在原语层面支持。
