### ISSUE TITLE
The display function is not output anything in the scheme session

### ISSUE THREAD

**Issue by littlewhite233** [XmacsLabs/mogan#528]
I insert a scheme session in the file.I try to play it like any kind of repl. But the display procedure doesn't output anything. 

```
Scheme]  (display "hello")

Scheme]  (display 3)

Scheme]  (display* 3)

Scheme]  (define a "hello world")

"hello world"
```

Expection:

```
Scheme] (display "hello world")
"hello world"
```

![image](https://user-images.githubusercontent.com/4672206/218324231-97389e0b-16a6-44c9-b895-2da1d1951390.png)

**Comment by Yufeng-shen** [comment]
If you launch Mogan from a terminal, you can see the Scheme outputs in the terminal
