### ISSUE TITLE
error while loading shared library libmogan.so

### ISSUE THREAD

**Issue by woutersj** [XmacsLabs/mogan#531]
Following the compilation instructions for GNU/Linux, I installed mogan to the `build/package` directory. The command `build/package/bin/mogan` then fails with the following error

``
build/package/bin/mogan: error while loading shared libraries: libmogan.so: cannot open shared object file: No such file or directory
``

**Comment by darcy-shen** [comment]
Yes. Using debug mode is the solution. And in the dev guide, I have documented it: https://github.com/XmacsLabs/mogan/blob/main/docs/guide/Develop_on_Linux.md

**Comment by darcy-shen** [comment]
If I do not use debug mode, sometimes, I may link to the installed libmogan.so, it is very confusing when developing. I still didn't find a good way to solve the problem.

**Comment by ProfFan** [comment]
I think you should report this to the xmake project, the built binaries should first be hard linked to the compiled binaries, and only at INSTALL time should the RPATH be changed to using system paths like `/usr/lib` etc.

**Comment by darcy-shen** [comment]
@waruqi Do you think it is a bug of xmake, or it is our wrong usage of xmake in mogan? I have to say I didn't learn xmake seriously, I just picked it up and made it work for Mogan.

**Comment by woutersj** [comment]
I get the same behaviour with the `xmake` shared library example program:
```
xmake create -l c -t shared test
cd test
xmake
xmake install -o ~/testxmake
~/testxmake/bin/test
```
results in
`error while loading shared libraries: libfoo.so: cannot open shared object file: No such file or directory`

**Comment by woutersj** [comment]
The [target:add_rpathdirs option](https://xmake.io/#/manual/project_target?id=targetadd_rpathdirs) seems useful.

Adding
``
add_rpathdirs("@executable_path/../lib")
``
to `target("mogan")` fixes it for me.

**Comment by waruqi** [comment]
> The [target:add_rpathdirs option](https://xmake.io/#/manual/project_target?id=targetadd_rpathdirs) seems useful.
> 
> Adding `add_rpathdirs("@executable_path/../lib")` to `target("mogan")` fixes it for me.

right, you can set rpathdir to modify it.

Although xmake install currently installs programs according to the `/bin`, `/lib` directory structure by default, it is possible to customise the installation structure.

The rpath setting is determined at compile time rather than at install time. Therefore xmake has no way of knowing in advance how the program will actually be installed by the user.

For example, for macOS app programs, it does not need `@executable_path/... /lib`.

Therefore, xmake does not set it by default; the user can set `add_rpathdirs("@executable_path/... /lib")`

**Comment by ProfFan** [comment]
@waruqi A saner default is to set the first RPATH to be the compile directory. When one needs to "install", for example with `xmake install` then xmake rewrites the first RPATH to `<install_prefix>/lib`

**Comment by darcy-shen** [comment]
will be fixed by: https://github.com/XmacsLabs/mogan/pull/1329
