### ISSUE TITLE
Some bugs about Mogan v1.1.1 on MacOS

### ISSUE THREAD

**Issue by ysyszheng** [XmacsLabs/mogan#540]
I'm using Mogan v1.1.1 on MacOS Ventura 13.2, and found some bugs. I'm not sure if these issues are fixed in the new version 1.1.2.
* `command +` shortcut key cannot zoom in
* `command E` shortcut key cannot center the text or picture
* `command W` shortcut not only closes the document, but also exits the application. But exiting the application should be the shortcut key `command Q`
* When the document language is selected as English, the entered Chinese text may exceed the page (when the text exceeds the length of one line, it will not wrap automatically)

Also, I have a suggestion about new features. I wonder if the developer has plans to integrate mogan's app menu into the macos menu bar? (As shown below)
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/77224524/227494207-75af62eb-b7e7-44d3-ae04-40d06723a798.png">

Thanks to the development team for maintaining this project! This project is awesome :)

**Comment by darcy-shen** [comment]
> When the document language is selected as English, the entered Chinese text may exceed the page (when the text exceeds the length of one line, it will not wrap automatically)

Fixed in v1.1.2.

**Comment by darcy-shen** [comment]
> Also, I have a suggestion about new features. I wonder if the developer has plans to integrate mogan's app menu into the macos menu bar? (As shown below)

See #47

**Comment by ysyszheng** [comment]
thank!
