### ISSUE TITLE
gs_to_png failed

### ISSUE THREAD

**Issue by ProfFan** [XmacsLabs/mogan#545]
```
Error:gs_to_png failed for ramdisc://image.ps
Error:ramdisc://image.ps could not be converted
```

ps_out 从 Python 输出出来的 figure 显示不出来，感觉是 Ghostscript 路径没找到？同环境（macOS Ventura）下 TM 是好的

**Comment by ProfFan** [comment]
@darcy-shen

**Comment by darcy-shen** [comment]
点击 Help -> Plugins -> Eukleides，里面的图像是ps格式的，可以确认是我这边是没有问题的。

然后我直接调用Mogan内置的gs命令行，可以看到可以正常调用：
```
$ /Applications/Mogan.app/Contents/Resources/share/Xmacs/bin/gs --version
9.54.0
```

**Comment by darcy-shen** [comment]
Discuss with the user via Wechat, it is a misuse of the pyenv plugin.

**Comment by ProfFan** [comment]
Tested again with working pyenv, same problem
<img width="996" alt="image" src="https://user-images.githubusercontent.com/5358374/230703433-8c95c7e7-edf4-4fdd-8cf6-ec29648cdfb4.png">

This is not with saved PS but generated by matplotlib online

**Comment by darcy-shen** [comment]
Please provide the detailed steps to re-produce the bug.
