### ISSUE TITLE
[71_35] UI becomes dark and hard to read after exciting presentation mode on MacOS. 

### ISSUE THREAD

**Issue by jmhimara** [XmacsLabs/mogan#546]
This seems to be a problem with both Mogan and TeXmacs on MacOS. Does not seem to happen on Windows.

After exiting presentation mode, the UI icons at the top of the window become dark and hard to read. See picture:

<img width="914" alt="Screenshot 2023-03-25 at 10 46 17 PM" src="https://user-images.githubusercontent.com/57339564/227757756-10ee40ea-99d3-4b7b-b792-3f5fe9e397d2.png">

**Comment by YiqiXu** [comment]
Thanks. It is a known issue. Temporarily you could fix this by changing the UI style to native through `Edit → Preferences... → General → User interface theme → Native`.

**Comment by darcy-shen** [comment]
Should be fixed by https://github.com/XmacsLabs/mogan/pull/1684

Please wait for Mogan v1.2.6 or Mogan v1.2.5.1
