### ISSUE TITLE
Cannot find `libdl` installed by msys pacman

### ISSUE THREAD

**Issue by pokyux** [XmacsLabs/mogan#567]
By default, pacman in msys installs files to path `/msys/mingw64` . I installed `libdl` via pacman and found `libdl` in `/msys/mingw64` .

However, mogan document says:

> CAUTIONS: Mingw in msys pacman is too new thus imconpatible for this project. Please install mingw 8.1.0 for this project, from either Qt installer or from chocolate.

So here is a problem: when executing the command from mogan document `xmake config --qt=<newly installed qt address>/5.x.x/mingw81_64` , xmake cannot find `libdl` and showed: `checking for libdl ... no`

Problem solved after moving files from `/msys/mingw64` to mingw in Qt folder. Xmake can find `libdl` now: `checking for libdl ... ok`

Would it be better to mention the operation above in mogan document? Or is there something wrong with my installation?

**Comment by jingkaimori** [comment]
Dynamic linking support for texmacs is unmaintained, so you can ignore this error message safely.
