### ISSUE TITLE
Compilation failed on win system_1

### ISSUE THREAD

**Issue by tangdouer1005** [XmacsLabs/mogan#571]
As the documentation says,
> Mingw in msys pacman is too new thus imconpatible for this project. Please install mingw 8.1.0 for this project, from either Qt installer or from chocolate.

I added `Tools\mingw810_64\bin` to the `PATH` environment variable. Although `gcc -v` can get the 8.1 version of gcc, but run`xmake config --qt=<newly installed qt address>/5.x.x/mingw81_64`, i get  `error: x86_64-w64-mingw32-g++: error: CreateProcess: No such file or directory`
So I downloaded gcc by command`pacman -S mingw-w64-x86_64-gcc`, but i get this
```
$ xmake config --qt=/D/qt_cp/5.15.2/mingw81_64
checking for platform ... mingw
checking for architecture ... x86_64
checking for mingw directory ... D:/msys/mingw64
checking for HAVE_UNISTD_H ... ok
checking for HAVE_MEMORY_H ... ok
checking for HAVE_SYS_STAT_H ... ok
checking for CONFIG_LARGE_POINTER ... ok
checking for HAVE_STDLIB_H ... ok
checking for HAVE_STRINGS_H ... ok
checking for HAVE_INTTYPES_H ... ok
checking for HAVE_SYS_TYPES_H ... ok
checking for HAVE_STDINT_H ... ok
checking for HAVE_GETTIMEOFDAY ... ok
checking for HAVE_UTIL_H ... no
checking for HAVE_PTY_H ... no
checking for HAVE_STRING_H ... ok
checking for HAVE_TIME_T ... ok
checking for HAVE_INTPTR_T ... ok
checking for libdl ... no
checking for Microsoft Visual Studio (x64) version ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> libcurl 7.84.0
  -> pdfhummus 4.1 [libpng:y, libjpeg:y]
please input: y (y/n/m)
y
  => download https://github.com/galkahana/PDF-Writer/archive/refs/tags/v4.1.tar.gz .. failed
  => install pdfhummus 4.1 .. failed

[  0%]: cache compiling.release PDFWriter\AbstractContentContext.cpp
[  0%]: cache compiling.release PDFWriter\ANSIFontWriter.cpp
[  0%]: cache compiling.release PDFWriter\ArrayOfInputStreamsStream.cpp
[  0%]: cache compiling.release PDFWriter\CharStringType1Tracer.cpp
[  0%]: cache compiling.release PDFWriter\CFFEmbeddedFontWriter.cpp
[  0%]: cache compiling.release PDFWriter\Ascii7Encoding.cpp
[  0%]: cache compiling.release PDFWriter\CFFPrimitiveReader.cpp
[  0%]: cache compiling.release PDFWriter\CFFANSIFontWriter.cpp
[  0%]: cache compiling.release PDFWriter\CFFFileInput.cpp
[  0%]: cache compiling.release PDFWriter\CFFDescendentFontWriter.cpp
[  0%]: cache compiling.release PDFWriter\CharStringType1Interpreter.cpp
[  0%]: cache compiling.release PDFWriter\CFFPrimitiveWriter.cpp
[  0%]: cache compiling.release PDFWriter\AbstractWrittenFont.cpp
[  0%]: cache compiling.release PDFWriter\CatalogInformation.cpp
error: D:/msys/mingw64/include/c++/12.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or dir
ectory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
if you want to get more verbose errors, please see:
  -> C:\Users\86159\AppData\Local\.xmake\cache\packages\2304\p\pdfhummus\4.1\installdir.failed\logs
\install.txt
error: install failed!
```
So is it because I downloaded a higher version of gcc through pacman in msys? 
But if I don't download it will error`error: x86_64-w64-mingw32-g++: error: CreateProcess: No such file or directory`.
where did i go wrong? TT

**Comment by pokyux** [comment]
These are my build commands, which copied from Github Actions.

```shell
xmake config --yes --verbose --diagnosis --plat=mingw --mingw=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/ --qt=/c/Qt5/5.15.2/mingw81_64/
xmake build --yes --verbose --diagnosis --jobs=4 --all
windeployqt --compiler-runtime ./build/mingw/x86_64/release/ -printsupport
xmake install mogan_install
windeployqt --compiler-runtime ./build/package/bin/ -printsupport
```

Notice: If you failed on building `libcurl`, you may try to remove these files and run those commands again.

```
/usr/include/libpsl.h
/usr/lib/libpsl.a
/usr/lib/libpsl.dll.a
/usr/lib/pkgconfig/libpsl.pc
/usr/share/man/man3/
```

By the way, Mingw installed by choco is version `8.1.0`.

**Comment by waruqi** [comment]
`D:/msys/mingw64` and `qt/5.x.x/mingw81_64` are two mingw toolchain, they may be in conflict. and you added `Tools\mingw810_64\bin` to PATH.

if you use msys, why do not use `pacman -Sy mingw-w64-x86_64-qt5`?

**Comment by tangdouer1005** [comment]
Thank you for your help. Now I understand the mistakes I made. What I understand is that two paths, `qt` and `mingw`, are required for compilation. If not specified, the path `/msys/mingw64` will be specified by default, and only putting the path in `PATH` is not enough.`xmake f` or `xmake config` is right.

I don't know if what I said above is correct

By the way, the mingw version I installed from choco is `12.2.0`, and I did not find the `8.10` version, but fortunately, the mingw version under `qt/tool` ​​is `8.10`, which solved my problem

**Comment by darcy-shen** [comment]
You'd better use the mingw shipped by Qt. @jingkaimori What's your idea?

**Comment by darcy-shen** [comment]
> if you use msys, why do not use `pacman -Sy mingw-w64-x86_64-qt5`?

I think installing Qt via pacman should be a better solution if we only develop on Mingw.

Because we are developing on Windows/Linux/macOS, installing Qt in the same way (`aqtinstall`) would be a good idea both for local development and CI.

**Comment by darcy-shen** [comment]
Here is the corresponding ticket on Gitee: https://gitee.com/XmacsLabs/mogan/issues/I6PBXJ

Please improve the doc for developing on Windows later when you have figured out how to compile it on Windows. @tangdouer1005

**Comment by tangdouer1005** [comment]
> Here is the corresponding ticket on Gitee: https://gitee.com/XmacsLabs/mogan/issues/I6PBXJ
> 
> Please improve the doc for developing on Windows later when you have figured out how to compile it on Windows. @tangdouer1005


With everyone's help, I have successfully compiled mogan, how can I improve the documentation now?

**Comment by darcy-shen** [comment]
just create pull requests on gitee/github/codeberg
