### ISSUE TITLE
The user manual cannot be opened in its usual settings.

### ISSUE THREAD

**Issue by strangeZombies** [XmacsLabs/mogan#576]
![2023-04-20 06 14 57](https://user-images.githubusercontent.com/63335673/233212026-87fa6c51-2102-4416-8d2d-1029a37661a0.png)
![2023-04-20 06 15 24](https://user-images.githubusercontent.com/63335673/233212032-d349fc81-c013-4d00-ac45-e5b553f75f5e.png)

platform: win11
version: [Mogan-v1.1.2-64bit-installer.exe]
(https://github.com/XmacsLabs/mogan/releases/download/v1.1.2/Mogan-v1.1.2-64bit-installer.exe)

**Comment by darcy-shen** [comment]
Full manuals support has been removed in Mogan Research v1.2.0. Thanks for reporting the bug.
