### ISSUE TITLE
Forum title is too dark in the dark mode.

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#66]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/32867606/148707176-3babe321-4739-4fc2-8ce1-0ca95600fbf1.png">

**Comment by darcy-shen** [comment]
This is a forum issue but not a Mogan Editor issue!

**Comment by YiqiXu** [comment]
I don't know where I should report it otherwise.

**Comment by darcy-shen** [comment]
Report to the forum directly: http://forum.texmacs.cn/c/site-feedback
