### ISSUE TITLE
Blank default interface without menu and toolbar under Mac

### ISSUE THREAD

**Issue by syrte** [XmacsLabs/mogan#661]
It is empty at the first launch, see the figure.
Is this the default interface? I'd say it is really confusing for a new user.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/7038335/235984475-98e69fb4-410d-4304-b64c-6fedad4ccbcc.png">

For those who met the same problem, here is the solution provided by [darcy](https://github.com/darcy-shen):
> ctrl 加 右键 可以打开菜单
> View这个菜单下可以选择显示或者隐藏 工具栏或者菜单

**Comment by darcy-shen** [comment]
> Is this the default interface?

No.

You can use `Ctrl+Right click` to enable the toolbar again in the `View` menu.
