### ISSUE TITLE
[59_11] Problem with tab completion in the `\ref` macro

### ISSUE THREAD

**Issue by TCLiuu** [XmacsLabs/mogan#691]
When the document language is set to Chinese and the cursor is positioned after certain vowel letters (such as "e"), using the `Tab` key in the `\ref` macro does not trigger the auto-completion correctly. Instead, it switches to the corresponding letters with accents. However, this issue does not occur in English mode.

**Comment by darcy-shen** [comment]
Fixed by #1424
