### ISSUE TITLE
Popularize Mogan/TeXmacs

### ISSUE THREAD

**Issue by YiqiXu** [XmacsLabs/mogan#692]
Let us discuss this issue of how we could popularize Mogan/TeXmacs.

**Comment by darcy-shen** [comment]
我目前正在做的事情是，通过开源之夏这个活动，让墨干这个项目在学生中形成良好的口碑。我希望来参加开源之夏的学生，能够通过参与墨干的开源之夏项目，获得成长。然后以后每年都可以有类似开源之夏的项目，这样可以有源源不断的年轻的开发者加入我们。

然后，今年我担任导师的项目是：http://forum.texmacs.cn/t/project-mogan-draw-on-wasm/1424 这个项目的目的就是让初中数学老师可以以极低的门槛，使用墨干里面的绘图功能，用于初中阶段几何相关的授课。

**Comment by TCLiuu** [comment]
我是在和超理论坛的人闲聊的时候了解到 Texmacs 的，不过入门主要是通过看一些介绍文章，例如[这篇](https://zhuanlan.zhihu.com/p/556849536)，这种文章的逻辑和很多 latex 的入门文章类似，开篇就介绍了 Texmacs 的特点、相较于 LaTex 的区别和优点，覆盖不少常用的用法，看过一遍之后马上就可以开始写，碰到的小问题可以很快查到或者解决，让使用体验进入正循环，我觉得这是非常重要的。
举个例子，我第一次用的时候，插入标题以后怎么也不会跳出这个标题环境，回车只能不断输入新行，查了一下才知道要用方向键跳出环境。而 Texmacs 现在的文档对于初学者和刚刚入门的用户来说还是太不友好了，信息量也小，很多问题不在社区里问就很难得到答案，如果能有一个从初学者角度出发的引导性文档，例如 vim 的 vimtutor，对提高用户留存率应该有不小的帮助。这也是我目前在做的事情，刚开始推动整理了一下 math symbol list，现在想整理一下 Q&A。在没有 math symbol list 之前，我想找某个符号怎么输入都得翻 kbd 文件（当时墨客星球里的符号表几乎起不到作用）。
此外想为视频提供一些评论，墨干的视频在宣传上应该是起到了不少作用，不过我觉得在功能宣传上不是很好用，视频的信息密度过于低下了，而且墨干的视频也没有时间线的标注，要找关于某个功能的介绍时，还得在时间线上反复拖拽寻找。另外我想从我个人的角度提一个问题，可能在很大的程度上有失偏颇，墨干的目标群体看视频的频率高吗？他们会倾向于通过视频来获得学术软件之类的信息吗？
