### ISSUE TITLE
plugins not working

### ISSUE THREAD

**Issue by pedrodiazsimal** [XmacsLabs/mogan#701]
Hi
I have tested the last version (1.1.3) and I see that most of the existing plugins do not work. (maxima, graphviz, xypic, dratex, python...) they even do not appear in the list.

Regards

**Comment by pdiazs** [comment]
This is the list of plugins in texmacs
https://i.imgur.com/jhYguQG.png
And this is the list in Mogan
https://i.imgur.com/VJz9VSX.png

In the same computer
Windows 10

**Comment by pdiazs** [comment]
Hi
And this is the list of plugins if we downgrade again to 1.1.2

https://i.imgur.com/WuXY8Cn.png

The same in 4 different computers all in windows
If there is any relevant information that ii have ommited, please let me know.
regards

**Comment by darcy-shen** [comment]
Confirmed by @jingkaimori . Thanks to report the issue, we will release Mogan Editor 1.1.4 soon.

**Comment by darcy-shen** [comment]
The Octave plugin works fine in Mogan Editor v1.1.3.

**Comment by pdiazs** [comment]
Yes it works, it is maxima and graphviz who do not work amomg others as you can see in my captures
regards

**Comment by darcy-shen** [comment]
It could be reproduced on branch-1.2, I will fix it as soon as possible. When releasing Mogan Editor 1.1.3, my environment for Windows is broken.

**Comment by darcy-shen** [comment]
Here is the root cause:
``` scheme
> (getenv "TEXMACS_PATH")
#f
```

**Comment by darcy-shen** [comment]
Here is the fix for the maxima plugin: https://github.com/XmacsLabs/mogan/pull/759

If you know how to apply a patch and install a plugin via TEXMACS_HOME_PATH, you may fix it by youself for now. Otherwise, please wait for Mogan Editor 1.1.4.

**Comment by pdiazs** [comment]
Hi 
Just trying to help, the problem ocurs with a set of plugins apart from maxima: graphviz, asymptote, dratex, xypic, graph, yacas, reduce.....

I see the fix points to maxima, but tex based graphics, and other graphics reproduce the problem

regards

**Comment by darcy-shen** [comment]
I know why it failed for other plugins. Because, in branch-1.2, I made the decision to maintain only a small subset of all the built-in plugins in GNU TeXmacs, see https://github.com/XmacsLabs/mogan/tree/branch-1.2/plugins :
+ cadabra
+ fricas
+ giac
+ maxima
+ octave
+ pari

And for branch-1.1, we still keep the plugins. I will fix it in `v1.1.4-rc1` soon for:
```
graphviz, asymptote, dratex, xypic, graph, yacas, reduce
```

**Comment by darcy-shen** [comment]
@pdiazs Try 1.1.4 rc1: https://github.com/XmacsLabs/mogan/releases/tag/v1.1.4-rc1

**Comment by pedrodiazsimal** [comment]
Hi
it works¡¡¡
Bravo¡¡¡¡
