### ISSUE TITLE
where is procedure-documentation defined at?

### ISSUE THREAD

**Issue by jingkaimori** [XmacsLabs/mogan#732]
`procedure-documentation` is used in [`tm-define.scm`](https://github.com/XmacsLabs/mogan/blob/a9a44b47c75d57e53b134b632e6fe3762d70a7ae/TeXmacs/progs/kernel/texmacs/tm-define.scm#L230-L231), but no definition is found. @mgubi

**Comment by darcy-shen** [comment]
I guess it is from guile. Functions related meta programming in GNU Guile still exists in the codebase of Mogan. This part is broken.

**Comment by jingkaimori** [comment]
It is confirmed to be [a procedure provided by Guile](https://www.gnu.org/software/guile/manual/guile.html#index-procedure_002ddocumentation). We should also check string literal at first line of procedure [like this](https://github.com/XmacsLabs/mogan/blob/a9a44b47c75d57e53b134b632e6fe3762d70a7ae/TeXmacs/progs/kernel/texmacs/tm-define.scm#L152).

**Comment by jingkaimori** [comment]
closed by 7ea0b5ee118343c2bf8dfd8fd587f0dce2a778e0

**Comment by jingkaimori** [comment]
closed by 7ea0b5ee118343c2bf8dfd8fd587f0dce2a778e0
