### ISSUE TITLE
Copying or exporting to LaTeX won't work on Windows

### ISSUE THREAD

**Issue by DongRih** [XmacsLabs/mogan#74]
* `File -> Export -> LaTeX...`
* `Edit -> Copy to -> LaTeX`

won't work.

**Comment by darcy-shen** [comment]
Which version are you using? Mogan v1.0-alpha4?

**Comment by DongRih** [comment]
I'm using Mogan v1.0-alpha4, and I found this only occurs when `block` or `tabular` appear in file or selection area: 

* `block` or `tabular` in file -> unable to export as LaTeX
* `block` or `tabular` in selection area -> unable to copy as LaTeX

![image](https://user-images.githubusercontent.com/35327409/150676468-ce47cc5f-5a90-497f-889d-d37175f61308.png)

**Comment by darcy-shen** [comment]
v1.2.3-rc2 (will be released this weekend) should work fine

**Comment by darcy-shen** [comment]
这是texmacs源代码
```
<\math>
  123123\<times\>123123

  123132<rsup|12313132>
</math>

<block|<tformat|<table|<row|<cell|123123>|<cell|123123>|<cell|123132>>>>>
```
对于的latex代码可以通过复制到latex得到：
```
$123123 \times 123123$

$123132^{12313132}$

\begin{tabular}{|l|l|l|}
  \hline
  123123 & 123123 & 123132\\
  \hline
\end{tabular}
```
