### ISSUE TITLE
404 on Contribution guide

### ISSUE THREAD

**Issue by Tiphereth-A** [XmacsLabs/mogan#776]
https://github.com/XmacsLabs/mogan/blob/ee29e30c1bd8a014d50d6430fd39db0ba6f6a6b4/README.md?plain=1#L27

https://github.com/XmacsLabs/mogan/blob/ee29e30c1bd8a014d50d6430fd39db0ba6f6a6b4/README_ZH.md?plain=1#L27

Both URLs (<https://mogan.app/guide/CONTRIBUTING.html> & <https://mogan.app/zh/guide/CONTRIBUTING.html>) return 404 when opened.

**Comment by darcy-shen** [comment]
https://github.com/XmacsLabs/mogan/blob/branch-1.2/CONTRIBUTING.md

We decided to maintain the developers' guide in the repo. Thanks for reporting the dead link!

**Comment by darcy-shen** [comment]
closed by #857
