### ISSUE TITLE
Installation error on Mac M1

### ISSUE THREAD

**Issue by labspc** [XmacsLabs/mogan#809]
https://gitee.com/XmacsLabs/mogan/attach_files/1430663/download  
gitee和github一样，适用于macOS M1的包，无法打开。
finder显示：无法打开“Mogan.app”，因为Apple无法检查其是否包含恶意软件。 
难道是因为我已经安装有 TeXmacs的缘故吗？已经试了好多次了。

**Comment by labspc** [comment]
没有试过，我是试试看。但是，为什么会出现这种问题呢？

**Comment by labspc** [comment]
无法解决，未出现Mogan.app was locked..  和 Open Anyway的按钮，安全性这块儿选择没有错误

**Comment by darcy-shen** [comment]
在我的M1上可以运行的，你的M1具体的macOS版本是什么？

**Comment by darcy-shen** [comment]
1.1.5我试了是可以的

**Comment by darcy-shen** [comment]
我的macOS是macOS 13.1 也是M1

**Comment by darcy-shen** [comment]
v1.2.5有试过么？

**Comment by da-liii** [comment]
感谢反馈！
