### ISSUE TITLE
[71_5] Can't open files consecutively

### ISSUE THREAD

**Issue by Oyyko** [XmacsLabs/mogan#817]
Env: archlinux+KDE.

Use the File --> Open function in the menu bar. Cannot continue to open the next file immediately after opening a new file. At present, my solution is to move the cursor to the file editing area and click once after opening a new file, so that I can continue to open the next new file.

Looking forward to: Someone can help to test whether the same problem exists on other platforms?

**Comment by darcy-shen** [comment]
It is a known bug on Linux. I tried but failed to find why.

**Comment by darcy-shen** [comment]
Should be fixed by https://github.com/XmacsLabs/mogan/commit/89eafaac81598d5991c0084f558d4cfd5d7c1bf0
