### ISSUE TITLE
[56_5] Using other editors to add macros in .ts files will not take effect.

### ISSUE THREAD

**Issue by Oyyko** [XmacsLabs/mogan#822]
If we have a .ts file, and we want to add a macro such as `<assign|hi|<macro|Hello world>>`. We must use mogan as our editor to add this macro. If we use vim/emacs/vscode as our editor, and we just add a line: `<assign|hi|<macro|Hello world>>`. It will not take effect.

That is because:

There are files in the cache that will record the information of the relevant macros.
This cache will only be refreshed when you need to use **mogan** to edit the ts file to add new macros.
Using **vscode** will not trigger the mechanism of refreshing the cache. You cannot use the new macro.
For me, `/home/oyyko/.texmacs/system/cache/__tmdoc__british__%home%oyyko%ospp%mogan%devel%devel__` is the cache file. You can find macro caches here.

---

The desired improvement is that the cache can be updated automatically.

**Comment by jingkaimori** [comment]
You can remove these cache by running mogan with `--delete-style-cache` option, further information could be found at #794 :

```sh
mogan --delete-style-cache
```

**Comment by darcy-shen** [comment]
> For me, /home/oyyko/.texmacs/system/cache/__tmdoc__british__%home%oyyko%ospp%mogan%devel%devel__ is the cache file. You can find macro caches here.

The cache file name should be determined by the digest (eg. md5) of the original file.

**Comment by darcy-shen** [comment]
To update styles without restarting Mogan, it is a new feature.
