### ISSUE TITLE
Problems with version 1.1.5

### ISSUE THREAD

**Issue by pedrodiazsimal** [XmacsLabs/mogan#931]
Hi

I have noticed that new version introduces this problem. It does not close if the file is not saved previously. i guess the window inviting to save the file is opened outside of the visible screen. The sound is heard but the screen is not seen.

In the drawing screen the circle instrument does not work. See the example

the code is printed on  the graph instead of the circle printed.
<carc|0|.|.>
I use windows 11
 

![2023-08-12 18_22_46-No name  8 _](https://github.com/XmacsLabs/mogan/assets/133880715/175095a4-617c-4d9d-b59a-2967468dbef5)

**Comment by darcy-shen** [comment]
Remove `%AppData%/Xmacs/system` and restart Mogan Editor. It is
a known issue.

**Comment by jingkaimori** [comment]
Or you can run mogan with `--delete-doc-cache` option:

```sh
mogan --delete-doc-cache
```

@darcy-shen Should options to remove cache be extracted to separate executable with GUI?

**Comment by darcy-shen** [comment]
cache mechanism will be redesigned in `branch-1.2`.

**Comment by Oyyko** [comment]
> 

When I run `build/linux/x86_64/release/mogan --delete-doc-cache`, it says `The required TEXMACS_PATH() does not exists`. Maybe this is because I am a developer not a user.

**Comment by darcy-shen** [comment]
> When I run build/linux/x86_64/release/mogan --delete-doc-cache, it says The required TEXMACS_PATH() does not exists.

`xmake run research` will supply the TEXMACS_PATH for you. If you want to launch it by yourself, you should provide the TEXMACS_PATH.

**Comment by darcy-shen** [comment]
We will release Mogan Editor 1.1.6 to solve this issue.

**Comment by darcy-shen** [comment]
It should be fixed. Try Mogan Editor v1.1.6 rc2: https://github.com/XmacsLabs/mogan/releases/tag/v1.1.6-rc2

**Comment by darcy-shen** [comment]
Fixed in https://github.com/XmacsLabs/mogan/releases/tag/v1.1.6
