### ISSUE TITLE
Compilation Error on macOS 12 (arm64) for Version 1.1

### ISSUE THREAD

**Issue by TCLiuu** [XmacsLabs/mogan#944]
### System Information:
* OS: macOS 12 (arm64)
* SQLite3 Version Installed via Homebrew: 3.42.0

### Issue Description:
While compiling the latest 1.1 version of this project on my macOS 12 machine with arm64 architecture, I encountered a compilation error. The error message is as follows:
```
++ arch
+ [[ arm64 == \a\r\m\6\4 ]]
+ MOGAN_APP=build/macosx/arm64/release/Mogan.app
+ MOGAN_GS=build/macosx/arm64/release/Mogan.app/Contents/Resources/share/Xmacs/bin/gs
++ arch
+ [[ arm64 == \a\r\m\6\4 ]]
+ build_mogan_xmake
+ xmake config --yes
checking for Xcode directory ... %s
checking for Codesign Identity of Xcode ... no
checking for HAVE_STRING_H ... ok
checking for HAVE_UNISTD_H ... ok
checking for HAVE_MEMORY_H ... ok
checking for HAVE_GETTIMEOFDAY ... ok
checking for HAVE_SYS_TYPES_H ... ok
checking for HAVE_UTIL_H ... ok
checking for HAVE_STDINT_H ... ok
checking for HAVE_STDLIB_H ... ok
checking for HAVE_INTTYPES_H ... ok
checking for CONFIG_LARGE_POINTER ... ok
checking for HAVE_INTPTR_T ... ok
checking for HAVE_STRINGS_H ... ok
checking for HAVE_SYS_STAT_H ... ok
checking for HAVE_PTY_H ... no
checking for HAVE_TIME_T ... ok
checking for libdl ... ok
note: the following packages were not found on your system, try again after installing them:
  -> sqlite3 3.39.0+200
```

Additional Context:
I have already installed sqlite3 version 3.42.0 via Homebrew. Is there a strict dependency on version 3.39.0 of sqlite3 for this project?

This issue seems to be introduced by the commit:
[Link to Commit](https://github.com/XmacsLabs/mogan/commit/c3d246b7ea052f32d5d12f19796fab13c8e72434#diff-1e65723e47b81d67c25a98980a10861a012068422521d2331e559e547a4e79cc)

Please advise on how to resolve this issue. Thank you!

**Comment by darcy-shen** [comment]
In branch-1.1:

``` lua
    if is_plat ("macosx") then
        add_requires("sqlite3", {system=true})
    else
        add_requires("sqlite3 3.39.0+200", {system=false})
    end
```
It means, it will use the system sqlite3 shipped in macOS.

**Comment by darcy-shen** [comment]
You may try branch-1.2, it should work fine.
